### ISSUE TITLE
Exception from HRESULT

### ISSUE THREAD

**Issue by haftado3** [XamlAnimatedGif/WpfAnimatedGif#55]
for this image :
[gif image](http://www.blackandginger.com/wp-content/uploads/2018/09/Group-1.gif)  

i get this error :  

System.Runtime.InteropServices.COMException: 'Exception from HRESULT: 0x88980003'

**Comment by thomaslevesque** [comment]
Hi @haftado3,

The image is very large, and WpfAnimatedGif prepares all frames in memory before displaying them, so it uses a lot of memory. When I try to load this image, I see the RAM usage rise to nearly 1.5 GB before it crashes.

Unfortunately, there's no way to fix it, short of completely rethinking how this library works. This is why I created another library, [XamlAnimatedGif](https://github.com/XamlAnimatedGif/XamlAnimatedGif), which renders the frames just in time to display them. It uses much less memory, but it's also much slower for large images. So unfortunately neither library will work very well for this image, because it's so large...
