### ISSUE TITLE
Crash application when reading specific gif

### ISSUE THREAD

**Issue by DIMBD-AKE** [XamlAnimatedGif/WpfAnimatedGif#81]
![google](https://user-images.githubusercontent.com/7136206/91882407-e13bfb00-ecbd-11ea-97f1-0e28fea4c156.gif)
I don't know if other gifs do that too, but when I read this it crashes

**Comment by thomaslevesque** [comment]
Hi @DIMBD-AKE,

I didn't reproduce the crash, but I can see that the image takes a very long time before it starts rendering, and uses huge amounts of RAM (4GB!!!).

It's a known problem that WpfAnimatedGif uses a lot of memory. This is because it prepares all frames in memory (uncompressed) before rendering anything. This image has 675 frames with a resolution of 1280x720, so... you can see where this is going. WpfAnimatedGif works fine for small GIFs with not too many frames, but it's definitely not suitable for large GIFs.

I suggest you try my other animated GIF library, which decodes frames on the fly: [XamlAnimatedGif](https://github.com/XamlAnimatedGif/XamlAnimatedGif/). It should work much better with this GIF.

(BTW, given the size and the number of frames, maybe you should consider converting the GIF to a video and play it with MediaElement)
