### ISSUE TITLE
Cache gif in memory so it plays instantly when shown

### ISSUE THREAD

**Issue by NickThissen** [XamlAnimatedGif/WpfAnimatedGif#95]
Hello,

I have a use-case where the user can 'dynamically' show an image from a set of gif files. The potential gif files to show are known at run-time and I want to pre-load / cache all gifs in memory when my application loads, such that when any (of the cached) files are shown on screen they play immediately.

Currently it looks like the gif does not start loading into memory until it becomes visible on screen, e.g. if its container control is about to become visible. The entire application hangs for a while and then continues when finished loading.

I am fine with using a lot of memory, memory is cheap and the intent is to pre-load all images and gifs into memory such that they can be shown immediately with no delay. 

For normal static images I am using the following to force them to load immediately instead of 'on demand'. I call this code on application start, once for each image in the list of potential images.
```                
var bmp = new BitmapImage();
using (var stream = File.OpenRead(filepath))
{
	bmp.BeginInit();
	bmp.CacheOption = BitmapCacheOption.OnLoad;
	bmp.StreamSource = stream;
	bmp.EndInit();
}
bmp.Freeze();
return bmp;
```

This seems to work for static images but it does not play nice with this gif library. When I use this for gifs it throws an exception that the file is closed and cannot load the gif when it is about to become visible:
_System.ObjectDisposedException: 'Cannot access a closed file.'_

I guess it has to do with the stream being closed already, but again this indicates that the loading is not happening on load but actually on demand (after the stream has already closed).

I circumvented the error by using an UriSource instead, but it still does not load the file into memory and only starts loading on demand.
```
var gif = new BitmapImage();
gif.BeginInit();
gif.UriCachePolicy = new System.Net.Cache.RequestCachePolicy(System.Net.Cache.RequestCacheLevel.BypassCache);
gif.CacheOption = BitmapCacheOption.OnLoad;
gif.CreateOptions = BitmapCreateOptions.IgnoreImageCache;
gif.UriSource = new Uri(Path);
gif.EndInit();
return gif;
```

I tried all the options for caching and loading but none of them seem to make a difference. Is this just hardcoded behavior of the library that it only starts loading the frames on demand instead of immediately? Is there any way I can force it to load into memory at will instead of on demand?

Thanks!

**Comment by thomaslevesque** [comment]
> I guess it has to do with the stream being closed already, but again this indicates that the loading is not happening on load but actually on demand (after the stream has already closed).

Indeed.
The problem is that I need to access the `GifBitmapDecoder` for the image. If the source image is a `BitmapFrame`, I can get the decoder from the `Decoder` property, but for other types there's no way to access it. This means I have to recreate a `GifBitmapDecoder` from the stream or URI from which the image was created.

So I think the best option for your scenario is to load the image as a `BitmapFrame`. This may seem counter-intuitive, since it represents a single frame, and an animated GIF has several frames. But it actually loads the whole GIF file, and the frames are accessible via the `Decoder` property.

If you use a `BitmapFrame` as the `AnimatedSource` property, WpfAnimatedGif should be able to get hold of the decoder without re-reading from the stream or URI:

```csharp
var BitmapFrame.Create(new Uri(Path), BitmapCreateOptions.None, BitmapCacheOption.OnLoad);
return gif;
```

**Comment by NickThissen** [comment]
Thanks for the prompt reply! Unfortunately it seems to make no difference and my UI is still hanging for a few seconds most times I try to show the gif. Maybe something else is going on then... I will investigate further.

**Comment by thomaslevesque** [comment]
Hi @NickThissen,

Actually, I'm not really surprised... It's not reading the file that takes time, it's preparing the frames.
In an optimized animated GIF (and most of them *are* optimized), most frames aren't complete; they only contain the part that changed compared to the previous frame. So WpfAnimatedGif doesn't directly display the frames as they are in the original GIF file, it needs to combine them to create an animation from the complete frames. This process can be quite heavy for large GIFs.

There's currently no mechanism in the library to keep the "prepared" frames in memory for quick display at a later time. That would be an interesting feature to add. I'll keep it mind, if I ever find time to work on it...

In the meantime, there _is_ a caching mechanism, but it's designed for the case where multiple `Image` controls display the same animated GIF (in that case the existing animation is reused). This isn't exactly what you need, but maybe you could take advantage of it:  load the GIFs in hidden `Image` controls, so that when you actually want to display the GIF on another (visible) `Image` control, it reuses the animation from the hidden one. I'm not sure it would work, but it's worth trying (note that the hidden image controls need to be in the visual tree, otherwise they won't be loaded)

**Comment by NickThissen** [comment]
That's an interesting thought that I had myself but quickly dismissed because it seemed extremely "dirty" lol. But I will try it out when I have a chance. Just one thing: should I use a separate Image control for each gif file, or can I just re-use one Image control to which I assign each AnimatedSource one by one? And if so, do I need to wait for the gifs to load or can I just load them one by one something like this?
```
foreach (var file in cache.Gifs)
{
    ImageBehavior.SetAnimatedSource(hiddenImage, file);
}
```

**Comment by thomaslevesque** [comment]
> because it seemed extremely "dirty"

Well, yes, I guess it is! But it might work...

> Just one thing: should I use a separate Image control for each gif file, or can I just re-use one Image control to which I assign each AnimatedSource one by one?

A separate image control for each gif. When an GIF is no longer used in an Image control, it's removed from the cache.

**Comment by NickThissen** [comment]
Small update: it seems to help a bit but still not fully smooth. More importantly, it seems I underestimated how much memory even a small gif takes up this way. I think I had only 2 gifs loaded (~few kB and one large one about 1 MB) and it immediately went to 1.5 GB of memory. I stand by my statement that memory is cheap but there is a limit lol... I am probably going to need to support up to 50 or 60 gifs and that would be way too much.

I am now trying out your XamlAnimatedGif instead, maybe I can make that work better. It seems there I have a similar problem that gifs take many seconds to load especially if I try to show several of them at once. 

For now I will close this with the remark that it is possible to do what I wanted but not practical due to memory concerns after all. Thanks for the help anyway!

**Comment by thomaslevesque** [comment]
Yes, memory usage has always been the main problem of this library... that was one of the reasons for creating XamlAnimatedGif, but it has its own issues (e.g. slower rendering for large GIFs)
