### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by TingtingG233** [XamlAnimatedGif/WpfAnimatedGif#97]
Hi it‘s really headache issue ，when I open and close a window and repeat for sevral times I can't imaging how much memory I have used. And even if I have called GC to collection the memory immediately when I want to leave the memory didn't relesed.
this is a small project to test the memory leak.  when you click hide it will call GC.
https://github.com/TingtingG233/GifTest/tree/master/GifTest

**Comment by thomaslevesque** [comment]
Hi @TingtingG233,

Have you tried profiling your application to see what was using memory?
The project you submitted is more complex than it could be, which makes it harder to locate the problem. The issue might not even be related to WpfAnimatedGif. Could you:
- try to reproduce the problem with a simpler project?
- try to use UriSource instead of StreamSource to specify the image and see if the problem still happens?

**Comment by TingtingG233** [comment]
Thanks for your reply. The project has content several ways to test memory leak.But you can see every part  is separated. I have tried all ways that can be to load the gif with WpfAnimatedGif. All of the ways have the same problem that is the memory won’t be related in a short time. If you need I can separate the project and make it a individual project.

**Comment by thomaslevesque** [comment]
Hi @TingtingG233,

I had a look at your project. Actually, there's no leak; the memory is released eventually:

![image](https://user-images.githubusercontent.com/1864281/158267412-3538001d-1fed-4234-ba0d-c02fbd8a36d1.png)

It's just that WPF doesn't give you any control on _when_ the memory is released. In Windows Forms, you can `Dispose()` an image, which releases the memory, but WPF doesn't provide a way to do that.

In any case, the problem has nothing to do with WpfAnimatedGif itself: you can observe the same problem without using WpfAnimatedGif, by just loading the GIF as a fixed image and displaying it in the `Image` control. The problem is just more visible with WpfAnimatedGif (because it loads all frames in memory instead of just the first one, and so uses more memory), but it's not caused by it.
